# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TradeRuns.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TradeRuns(object):
    def setupUi(self, TradeRuns):
        TradeRuns.setObjectName("TradeRuns")
        TradeRuns.resize(805, 316)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TradeRuns.sizePolicy().hasHeightForWidth())
        TradeRuns.setSizePolicy(sizePolicy)
        TradeRuns.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("rsc/starclitz-logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TradeRuns.setWindowIcon(icon)
        TradeRuns.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(TradeRuns)
        self.centralwidget.setMinimumSize(QtCore.QSize(805, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(3, 1, 3, 1)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayoutBalanceBar = QtWidgets.QHBoxLayout()
        self.horizontalLayoutBalanceBar.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayoutBalanceBar.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayoutBalanceBar.setSpacing(3)
        self.horizontalLayoutBalanceBar.setObjectName("horizontalLayoutBalanceBar")
        self.labelBalance = QtWidgets.QLabel(self.centralwidget)
        self.labelBalance.setObjectName("labelBalance")
        self.horizontalLayoutBalanceBar.addWidget(self.labelBalance)
        self.lineEditBalance = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditBalance.sizePolicy().hasHeightForWidth())
        self.lineEditBalance.setSizePolicy(sizePolicy)
        self.lineEditBalance.setClearButtonEnabled(True)
        self.lineEditBalance.setObjectName("lineEditBalance")
        self.horizontalLayoutBalanceBar.addWidget(self.lineEditBalance)
        self.pushButtonBalanceSave = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonBalanceSave.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("rsc/save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonBalanceSave.setIcon(icon1)
        self.pushButtonBalanceSave.setFlat(True)
        self.pushButtonBalanceSave.setObjectName("pushButtonBalanceSave")
        self.horizontalLayoutBalanceBar.addWidget(self.pushButtonBalanceSave)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutBalanceBar.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayoutBalanceBar)
        self.horizontalLayoutLocations = QtWidgets.QHBoxLayout()
        self.horizontalLayoutLocations.setObjectName("horizontalLayoutLocations")
        self.groupBoxBuying = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxBuying.sizePolicy().hasHeightForWidth())
        self.groupBoxBuying.setSizePolicy(sizePolicy)
        self.groupBoxBuying.setObjectName("groupBoxBuying")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBoxBuying)
        self.verticalLayout.setContentsMargins(6, 1, 3, 3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayoutBuyingRow1 = QtWidgets.QGridLayout()
        self.gridLayoutBuyingRow1.setObjectName("gridLayoutBuyingRow1")
        self.comboBoxBuyCommodity = QtWidgets.QComboBox(self.groupBoxBuying)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxBuyCommodity.sizePolicy().hasHeightForWidth())
        self.comboBoxBuyCommodity.setSizePolicy(sizePolicy)
        self.comboBoxBuyCommodity.setEditable(True)
        self.comboBoxBuyCommodity.setObjectName("comboBoxBuyCommodity")
        self.gridLayoutBuyingRow1.addWidget(self.comboBoxBuyCommodity, 1, 1, 1, 1)
        self.labelBuyCommodity = QtWidgets.QLabel(self.groupBoxBuying)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelBuyCommodity.sizePolicy().hasHeightForWidth())
        self.labelBuyCommodity.setSizePolicy(sizePolicy)
        self.labelBuyCommodity.setObjectName("labelBuyCommodity")
        self.gridLayoutBuyingRow1.addWidget(self.labelBuyCommodity, 1, 0, 1, 1)
        self.labelBuyLocation = QtWidgets.QLabel(self.groupBoxBuying)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelBuyLocation.sizePolicy().hasHeightForWidth())
        self.labelBuyLocation.setSizePolicy(sizePolicy)
        self.labelBuyLocation.setMinimumSize(QtCore.QSize(0, 0))
        self.labelBuyLocation.setObjectName("labelBuyLocation")
        self.gridLayoutBuyingRow1.addWidget(self.labelBuyLocation, 0, 0, 1, 1)
        self.lineEditBuyCommodityPrice = QtWidgets.QLineEdit(self.groupBoxBuying)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditBuyCommodityPrice.sizePolicy().hasHeightForWidth())
        self.lineEditBuyCommodityPrice.setSizePolicy(sizePolicy)
        self.lineEditBuyCommodityPrice.setObjectName("lineEditBuyCommodityPrice")
        self.gridLayoutBuyingRow1.addWidget(self.lineEditBuyCommodityPrice, 1, 2, 1, 1)
        self.pushButtonBuyCommodityPriceSave = QtWidgets.QPushButton(self.groupBoxBuying)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBuyCommodityPriceSave.sizePolicy().hasHeightForWidth())
        self.pushButtonBuyCommodityPriceSave.setSizePolicy(sizePolicy)
        self.pushButtonBuyCommodityPriceSave.setText("")
        self.pushButtonBuyCommodityPriceSave.setIcon(icon1)
        self.pushButtonBuyCommodityPriceSave.setFlat(True)
        self.pushButtonBuyCommodityPriceSave.setObjectName("pushButtonBuyCommodityPriceSave")
        self.gridLayoutBuyingRow1.addWidget(self.pushButtonBuyCommodityPriceSave, 1, 3, 1, 1)
        self.comboBoxBuyLocation = QtWidgets.QComboBox(self.groupBoxBuying)
        self.comboBoxBuyLocation.setEditable(True)
        self.comboBoxBuyLocation.setObjectName("comboBoxBuyLocation")
        self.gridLayoutBuyingRow1.addWidget(self.comboBoxBuyLocation, 0, 1, 1, 2)
        self.pushButtonBuyLocationExpand = QtWidgets.QPushButton(self.groupBoxBuying)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBuyLocationExpand.sizePolicy().hasHeightForWidth())
        self.pushButtonBuyLocationExpand.setSizePolicy(sizePolicy)
        self.pushButtonBuyLocationExpand.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButtonBuyLocationExpand.setObjectName("pushButtonBuyLocationExpand")
        self.gridLayoutBuyingRow1.addWidget(self.pushButtonBuyLocationExpand, 0, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayoutBuyingRow1)
        self.horizontalLayoutBuyingRow2 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutBuyingRow2.setObjectName("horizontalLayoutBuyingRow2")
        self.lineEditBuySupply = QtWidgets.QLineEdit(self.groupBoxBuying)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditBuySupply.sizePolicy().hasHeightForWidth())
        self.lineEditBuySupply.setSizePolicy(sizePolicy)
        self.lineEditBuySupply.setObjectName("lineEditBuySupply")
        self.horizontalLayoutBuyingRow2.addWidget(self.lineEditBuySupply)
        self.pushButtonBuySupplySave = QtWidgets.QPushButton(self.groupBoxBuying)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonBuySupplySave.sizePolicy().hasHeightForWidth())
        self.pushButtonBuySupplySave.setSizePolicy(sizePolicy)
        self.pushButtonBuySupplySave.setText("")
        self.pushButtonBuySupplySave.setIcon(icon1)
        self.pushButtonBuySupplySave.setFlat(True)
        self.pushButtonBuySupplySave.setObjectName("pushButtonBuySupplySave")
        self.horizontalLayoutBuyingRow2.addWidget(self.pushButtonBuySupplySave)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutBuyingRow2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayoutBuyingRow2)
        self.horizontalLayoutBuyingRow3 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutBuyingRow3.setObjectName("horizontalLayoutBuyingRow3")
        self.lineEditBuyUnitCount = QtWidgets.QLineEdit(self.groupBoxBuying)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditBuyUnitCount.sizePolicy().hasHeightForWidth())
        self.lineEditBuyUnitCount.setSizePolicy(sizePolicy)
        self.lineEditBuyUnitCount.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditBuyUnitCount.setObjectName("lineEditBuyUnitCount")
        self.horizontalLayoutBuyingRow3.addWidget(self.lineEditBuyUnitCount)
        self.labelBuySliderLow = QtWidgets.QLabel(self.groupBoxBuying)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelBuySliderLow.sizePolicy().hasHeightForWidth())
        self.labelBuySliderLow.setSizePolicy(sizePolicy)
        self.labelBuySliderLow.setMaximumSize(QtCore.QSize(5, 16777215))
        self.labelBuySliderLow.setObjectName("labelBuySliderLow")
        self.horizontalLayoutBuyingRow3.addWidget(self.labelBuySliderLow)
        self.horizontalSliderBuyUnitCount = QtWidgets.QSlider(self.groupBoxBuying)
        self.horizontalSliderBuyUnitCount.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderBuyUnitCount.setObjectName("horizontalSliderBuyUnitCount")
        self.horizontalLayoutBuyingRow3.addWidget(self.horizontalSliderBuyUnitCount)
        self.labelBuySliderHigh = QtWidgets.QLabel(self.groupBoxBuying)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelBuySliderHigh.sizePolicy().hasHeightForWidth())
        self.labelBuySliderHigh.setSizePolicy(sizePolicy)
        self.labelBuySliderHigh.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelBuySliderHigh.setObjectName("labelBuySliderHigh")
        self.horizontalLayoutBuyingRow3.addWidget(self.labelBuySliderHigh)
        self.pushButtonBuyUnitsFill = QtWidgets.QPushButton(self.groupBoxBuying)
        self.pushButtonBuyUnitsFill.setDefault(False)
        self.pushButtonBuyUnitsFill.setFlat(False)
        self.pushButtonBuyUnitsFill.setObjectName("pushButtonBuyUnitsFill")
        self.horizontalLayoutBuyingRow3.addWidget(self.pushButtonBuyUnitsFill)
        self.verticalLayout.addLayout(self.horizontalLayoutBuyingRow3)
        self.horizontalLayoutLocations.addWidget(self.groupBoxBuying)
        self.groupBoxSelling = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxSelling.sizePolicy().hasHeightForWidth())
        self.groupBoxSelling.setSizePolicy(sizePolicy)
        self.groupBoxSelling.setObjectName("groupBoxSelling")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxSelling)
        self.verticalLayout_2.setContentsMargins(6, 1, 3, 3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayoutSellingRow1 = QtWidgets.QGridLayout()
        self.gridLayoutSellingRow1.setObjectName("gridLayoutSellingRow1")
        self.lineEditSellCommodityPrice = QtWidgets.QLineEdit(self.groupBoxSelling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSellCommodityPrice.sizePolicy().hasHeightForWidth())
        self.lineEditSellCommodityPrice.setSizePolicy(sizePolicy)
        self.lineEditSellCommodityPrice.setObjectName("lineEditSellCommodityPrice")
        self.gridLayoutSellingRow1.addWidget(self.lineEditSellCommodityPrice, 1, 2, 1, 1)
        self.labelSellLocation = QtWidgets.QLabel(self.groupBoxSelling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSellLocation.sizePolicy().hasHeightForWidth())
        self.labelSellLocation.setSizePolicy(sizePolicy)
        self.labelSellLocation.setObjectName("labelSellLocation")
        self.gridLayoutSellingRow1.addWidget(self.labelSellLocation, 0, 0, 1, 1)
        self.comboBoxSellCommodity = QtWidgets.QComboBox(self.groupBoxSelling)
        self.comboBoxSellCommodity.setEditable(True)
        self.comboBoxSellCommodity.setObjectName("comboBoxSellCommodity")
        self.gridLayoutSellingRow1.addWidget(self.comboBoxSellCommodity, 1, 1, 1, 1)
        self.labelSellCommodity = QtWidgets.QLabel(self.groupBoxSelling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSellCommodity.sizePolicy().hasHeightForWidth())
        self.labelSellCommodity.setSizePolicy(sizePolicy)
        self.labelSellCommodity.setObjectName("labelSellCommodity")
        self.gridLayoutSellingRow1.addWidget(self.labelSellCommodity, 1, 0, 1, 1)
        self.pushButtonSellCommoditySave = QtWidgets.QPushButton(self.groupBoxSelling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSellCommoditySave.sizePolicy().hasHeightForWidth())
        self.pushButtonSellCommoditySave.setSizePolicy(sizePolicy)
        self.pushButtonSellCommoditySave.setText("")
        self.pushButtonSellCommoditySave.setIcon(icon1)
        self.pushButtonSellCommoditySave.setFlat(True)
        self.pushButtonSellCommoditySave.setObjectName("pushButtonSellCommoditySave")
        self.gridLayoutSellingRow1.addWidget(self.pushButtonSellCommoditySave, 1, 3, 1, 1)
        self.comboBoxSellLocation = QtWidgets.QComboBox(self.groupBoxSelling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxSellLocation.sizePolicy().hasHeightForWidth())
        self.comboBoxSellLocation.setSizePolicy(sizePolicy)
        self.comboBoxSellLocation.setEditable(True)
        self.comboBoxSellLocation.setObjectName("comboBoxSellLocation")
        self.gridLayoutSellingRow1.addWidget(self.comboBoxSellLocation, 0, 1, 1, 2)
        self.pushButtonSellLocationExpand = QtWidgets.QPushButton(self.groupBoxSelling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSellLocationExpand.sizePolicy().hasHeightForWidth())
        self.pushButtonSellLocationExpand.setSizePolicy(sizePolicy)
        self.pushButtonSellLocationExpand.setMaximumSize(QtCore.QSize(25, 16777215))
        self.pushButtonSellLocationExpand.setObjectName("pushButtonSellLocationExpand")
        self.gridLayoutSellingRow1.addWidget(self.pushButtonSellLocationExpand, 0, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayoutSellingRow1)
        self.horizontalLayoutSellingRow2 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutSellingRow2.setObjectName("horizontalLayoutSellingRow2")
        self.lineEditSellDemand = QtWidgets.QLineEdit(self.groupBoxSelling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSellDemand.sizePolicy().hasHeightForWidth())
        self.lineEditSellDemand.setSizePolicy(sizePolicy)
        self.lineEditSellDemand.setObjectName("lineEditSellDemand")
        self.horizontalLayoutSellingRow2.addWidget(self.lineEditSellDemand)
        self.pushButtonSellDemandSave = QtWidgets.QPushButton(self.groupBoxSelling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSellDemandSave.sizePolicy().hasHeightForWidth())
        self.pushButtonSellDemandSave.setSizePolicy(sizePolicy)
        self.pushButtonSellDemandSave.setText("")
        self.pushButtonSellDemandSave.setIcon(icon1)
        self.pushButtonSellDemandSave.setFlat(True)
        self.pushButtonSellDemandSave.setObjectName("pushButtonSellDemandSave")
        self.horizontalLayoutSellingRow2.addWidget(self.pushButtonSellDemandSave)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutSellingRow2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayoutSellingRow2)
        self.horizontalLayoutSellingRow3 = QtWidgets.QHBoxLayout()
        self.horizontalLayoutSellingRow3.setObjectName("horizontalLayoutSellingRow3")
        self.lineEditSellUnitCount = QtWidgets.QLineEdit(self.groupBoxSelling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSellUnitCount.sizePolicy().hasHeightForWidth())
        self.lineEditSellUnitCount.setSizePolicy(sizePolicy)
        self.lineEditSellUnitCount.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditSellUnitCount.setObjectName("lineEditSellUnitCount")
        self.horizontalLayoutSellingRow3.addWidget(self.lineEditSellUnitCount)
        self.labelSellSliderLow = QtWidgets.QLabel(self.groupBoxSelling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSellSliderLow.sizePolicy().hasHeightForWidth())
        self.labelSellSliderLow.setSizePolicy(sizePolicy)
        self.labelSellSliderLow.setMaximumSize(QtCore.QSize(5, 16777215))
        self.labelSellSliderLow.setObjectName("labelSellSliderLow")
        self.horizontalLayoutSellingRow3.addWidget(self.labelSellSliderLow)
        self.horizontalSliderSellUnitCount = QtWidgets.QSlider(self.groupBoxSelling)
        self.horizontalSliderSellUnitCount.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderSellUnitCount.setObjectName("horizontalSliderSellUnitCount")
        self.horizontalLayoutSellingRow3.addWidget(self.horizontalSliderSellUnitCount)
        self.labelSellSliderHigh = QtWidgets.QLabel(self.groupBoxSelling)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSellSliderHigh.sizePolicy().hasHeightForWidth())
        self.labelSellSliderHigh.setSizePolicy(sizePolicy)
        self.labelSellSliderHigh.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelSellSliderHigh.setObjectName("labelSellSliderHigh")
        self.horizontalLayoutSellingRow3.addWidget(self.labelSellSliderHigh)
        self.pushButtonSellUnitsAll = QtWidgets.QPushButton(self.groupBoxSelling)
        self.pushButtonSellUnitsAll.setObjectName("pushButtonSellUnitsAll")
        self.horizontalLayoutSellingRow3.addWidget(self.pushButtonSellUnitsAll)
        self.verticalLayout_2.addLayout(self.horizontalLayoutSellingRow3)
        self.horizontalLayoutLocations.addWidget(self.groupBoxSelling)
        self.verticalLayout_3.addLayout(self.horizontalLayoutLocations)
        self.horizontalLayoutShipAndButtons = QtWidgets.QHBoxLayout()
        self.horizontalLayoutShipAndButtons.setObjectName("horizontalLayoutShipAndButtons")
        self.groupBoxShip = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxShip.setObjectName("groupBoxShip")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBoxShip)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBoxShip = QtWidgets.QComboBox(self.groupBoxShip)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxShip.sizePolicy().hasHeightForWidth())
        self.comboBoxShip.setSizePolicy(sizePolicy)
        self.comboBoxShip.setEditable(True)
        self.comboBoxShip.setCurrentText("")
        self.comboBoxShip.setObjectName("comboBoxShip")
        self.gridLayout.addWidget(self.comboBoxShip, 1, 1, 1, 1)
        self.pushButtonShipSave = QtWidgets.QPushButton(self.groupBoxShip)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonShipSave.sizePolicy().hasHeightForWidth())
        self.pushButtonShipSave.setSizePolicy(sizePolicy)
        self.pushButtonShipSave.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("save.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonShipSave.setIcon(icon2)
        self.pushButtonShipSave.setFlat(True)
        self.pushButtonShipSave.setObjectName("pushButtonShipSave")
        self.gridLayout.addWidget(self.pushButtonShipSave, 1, 3, 1, 1)
        self.pushButtonQTFuelSave = QtWidgets.QPushButton(self.groupBoxShip)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonQTFuelSave.sizePolicy().hasHeightForWidth())
        self.pushButtonQTFuelSave.setSizePolicy(sizePolicy)
        self.pushButtonQTFuelSave.setText("")
        self.pushButtonQTFuelSave.setIcon(icon2)
        self.pushButtonQTFuelSave.setFlat(True)
        self.pushButtonQTFuelSave.setObjectName("pushButtonQTFuelSave")
        self.gridLayout.addWidget(self.pushButtonQTFuelSave, 3, 3, 1, 1)
        self.lineEditSCUCapacity = QtWidgets.QLineEdit(self.groupBoxShip)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditSCUCapacity.sizePolicy().hasHeightForWidth())
        self.lineEditSCUCapacity.setSizePolicy(sizePolicy)
        self.lineEditSCUCapacity.setObjectName("lineEditSCUCapacity")
        self.gridLayout.addWidget(self.lineEditSCUCapacity, 1, 2, 1, 1)
        self.comboBoxQTDrive = QtWidgets.QComboBox(self.groupBoxShip)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxQTDrive.sizePolicy().hasHeightForWidth())
        self.comboBoxQTDrive.setSizePolicy(sizePolicy)
        self.comboBoxQTDrive.setEditable(True)
        self.comboBoxQTDrive.setCurrentText("")
        self.comboBoxQTDrive.setObjectName("comboBoxQTDrive")
        self.gridLayout.addWidget(self.comboBoxQTDrive, 3, 1, 1, 1)
        self.lineEditQTFuel = QtWidgets.QLineEdit(self.groupBoxShip)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditQTFuel.sizePolicy().hasHeightForWidth())
        self.lineEditQTFuel.setSizePolicy(sizePolicy)
        self.lineEditQTFuel.setObjectName("lineEditQTFuel")
        self.gridLayout.addWidget(self.lineEditQTFuel, 3, 2, 1, 1)
        self.labelQTDrive = QtWidgets.QLabel(self.groupBoxShip)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelQTDrive.sizePolicy().hasHeightForWidth())
        self.labelQTDrive.setSizePolicy(sizePolicy)
        self.labelQTDrive.setObjectName("labelQTDrive")
        self.gridLayout.addWidget(self.labelQTDrive, 3, 0, 1, 1)
        self.labelShip = QtWidgets.QLabel(self.groupBoxShip)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelShip.sizePolicy().hasHeightForWidth())
        self.labelShip.setSizePolicy(sizePolicy)
        self.labelShip.setObjectName("labelShip")
        self.gridLayout.addWidget(self.labelShip, 1, 0, 1, 1)
        self.horizontalLayoutShipAndButtons.addWidget(self.groupBoxShip)
        self.pushButtonCalculateRun = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonCalculateRun.sizePolicy().hasHeightForWidth())
        self.pushButtonCalculateRun.setSizePolicy(sizePolicy)
        self.pushButtonCalculateRun.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonCalculateRun.setFont(font)
        self.pushButtonCalculateRun.setObjectName("pushButtonCalculateRun")
        self.horizontalLayoutShipAndButtons.addWidget(self.pushButtonCalculateRun)
        self.pushButtonFindRun = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonFindRun.sizePolicy().hasHeightForWidth())
        self.pushButtonFindRun.setSizePolicy(sizePolicy)
        self.pushButtonFindRun.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonFindRun.setFont(font)
        self.pushButtonFindRun.setObjectName("pushButtonFindRun")
        self.horizontalLayoutShipAndButtons.addWidget(self.pushButtonFindRun)
        self.verticalLayout_3.addLayout(self.horizontalLayoutShipAndButtons)
        self.horizontalLayoutSummary = QtWidgets.QHBoxLayout()
        self.horizontalLayoutSummary.setObjectName("horizontalLayoutSummary")
        self.groupBoxSummary = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBoxSummary.setObjectName("groupBoxSummary")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBoxSummary)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.labelSummaryCapital = QtWidgets.QLabel(self.groupBoxSummary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSummaryCapital.sizePolicy().hasHeightForWidth())
        self.labelSummaryCapital.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.labelSummaryCapital.setFont(font)
        self.labelSummaryCapital.setObjectName("labelSummaryCapital")
        self.gridLayout_4.addWidget(self.labelSummaryCapital, 0, 0, 1, 1)
        self.labelSummaryCapitalValue = QtWidgets.QLabel(self.groupBoxSummary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSummaryCapitalValue.sizePolicy().hasHeightForWidth())
        self.labelSummaryCapitalValue.setSizePolicy(sizePolicy)
        self.labelSummaryCapitalValue.setObjectName("labelSummaryCapitalValue")
        self.gridLayout_4.addWidget(self.labelSummaryCapitalValue, 0, 1, 1, 1)
        self.labelSummaryActualProfit = QtWidgets.QLabel(self.groupBoxSummary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSummaryActualProfit.sizePolicy().hasHeightForWidth())
        self.labelSummaryActualProfit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setUnderline(True)
        self.labelSummaryActualProfit.setFont(font)
        self.labelSummaryActualProfit.setObjectName("labelSummaryActualProfit")
        self.gridLayout_4.addWidget(self.labelSummaryActualProfit, 0, 2, 1, 1)
        self.labelSummaryActualProfitValue = QtWidgets.QLabel(self.groupBoxSummary)
        self.labelSummaryActualProfitValue.setObjectName("labelSummaryActualProfitValue")
        self.gridLayout_4.addWidget(self.labelSummaryActualProfitValue, 0, 3, 1, 1)
        self.horizontalLayoutSummary.addWidget(self.groupBoxSummary)
        self.verticalLayout_3.addLayout(self.horizontalLayoutSummary)
        spacerItem3 = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        TradeRuns.setCentralWidget(self.centralwidget)

        self.retranslateUi(TradeRuns)
        QtCore.QMetaObject.connectSlotsByName(TradeRuns)

    def retranslateUi(self, TradeRuns):
        _translate = QtCore.QCoreApplication.translate
        TradeRuns.setWindowTitle(_translate("TradeRuns", "Starclitz Calculator - Trade runs"))
        self.labelBalance.setText(_translate("TradeRuns", "Balance"))
        self.groupBoxBuying.setTitle(_translate("TradeRuns", "Buying"))
        self.labelBuyCommodity.setText(_translate("TradeRuns", "Select Commodity"))
        self.labelBuyLocation.setText(_translate("TradeRuns", "Select Location"))
        self.lineEditBuyCommodityPrice.setPlaceholderText(_translate("TradeRuns", "Buy price"))
        self.pushButtonBuyLocationExpand.setText(_translate("TradeRuns", "..."))
        self.lineEditBuySupply.setPlaceholderText(_translate("TradeRuns", "Est. Supply"))
        self.lineEditBuyUnitCount.setPlaceholderText(_translate("TradeRuns", "Unit(s)"))
        self.labelBuySliderLow.setText(_translate("TradeRuns", "0"))
        self.labelBuySliderHigh.setText(_translate("TradeRuns", "98000"))
        self.pushButtonBuyUnitsFill.setText(_translate("TradeRuns", "Fill"))
        self.groupBoxSelling.setTitle(_translate("TradeRuns", "Selling"))
        self.lineEditSellCommodityPrice.setPlaceholderText(_translate("TradeRuns", "Buy price"))
        self.labelSellLocation.setText(_translate("TradeRuns", "Select Location"))
        self.labelSellCommodity.setText(_translate("TradeRuns", "Select Commodity"))
        self.pushButtonSellLocationExpand.setText(_translate("TradeRuns", "..."))
        self.lineEditSellDemand.setPlaceholderText(_translate("TradeRuns", "Est. Demand"))
        self.lineEditSellUnitCount.setPlaceholderText(_translate("TradeRuns", "Unit(s)"))
        self.labelSellSliderLow.setText(_translate("TradeRuns", "0"))
        self.labelSellSliderHigh.setText(_translate("TradeRuns", "98000"))
        self.pushButtonSellUnitsAll.setText(_translate("TradeRuns", "All"))
        self.groupBoxShip.setTitle(_translate("TradeRuns", "Ship Details"))
        self.lineEditSCUCapacity.setPlaceholderText(_translate("TradeRuns", "SCU Capacity"))
        self.lineEditQTFuel.setPlaceholderText(_translate("TradeRuns", "QT Fuel"))
        self.labelQTDrive.setText(_translate("TradeRuns", "Select QT Drive"))
        self.labelShip.setText(_translate("TradeRuns", "Select Ship"))
        self.pushButtonCalculateRun.setText(_translate("TradeRuns", "Calculate Run"))
        self.pushButtonFindRun.setText(_translate("TradeRuns", "Find Best Run"))
        self.groupBoxSummary.setTitle(_translate("TradeRuns", "Summary"))
        self.labelSummaryCapital.setText(_translate("TradeRuns", "Required Capital:"))
        self.labelSummaryCapitalValue.setText(_translate("TradeRuns", "x UEC"))
        self.labelSummaryActualProfit.setText(_translate("TradeRuns", "Actual Profit:"))
        self.labelSummaryActualProfitValue.setText(_translate("TradeRuns", "x UEC x %"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TradeRuns = QtWidgets.QMainWindow()
    ui = Ui_TradeRuns()
    ui.setupUi(TradeRuns)
    TradeRuns.show()
    sys.exit(app.exec_())
